export default {
	state : {
		popupmean:false,
		popupmean_more:-1,
		report:false,
		pic_text_video:false,
		share:false,
		blogs:{
			userseq:null,//用户自己的seq
			remark:null,//
			touserseq:null,
			friend:null//是否是好友
		}
	},
	mutations: {
		changepopupmean(state){
			state.popupmean=!state.popupmean;
		},
		changepopupmean_more(state,index){
			state.popupmean_more=index;
		},
		changereport(state){
			state.report=!state.report;
		},
		changepictextvideo(state){
			state.pic_text_video=!state.pic_text_video;
		},
		changeshare(state){
			state.share=!state.share;
		},
		setblog_remark(state,remark){
			state.blogs.remark=remark
		},
		setblog_touserseq(state,touserseq){
			state.blogs.touserseq=touserseq
		},
		setblog_friend(state,friend){
			state.blogs.friend=friend
		},
		setblog_userseq(state){
			state.blogs.userseq=JSON.parse(localStorage.getItem('loginInfo'))?JSON.parse(localStorage.getItem('loginInfo')).userseq:null
		}
	}
}